version: '3.8'
# This compose file is not for building images,
# only for running integration tests

services:
  postgres:
    image: postgres:13.4-alpine3.14
    volumes:
      - ./postgres/1.init.sql:/docker-entrypoint-initdb.d/1.init.sql
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notepad

  backend:
    # image: ...

  frontend:
    # image: ...
