version: '3.8'
# This compose file is for building production docker images on CI (Github Actions)
# Not for running any of them, only for building

services:
  backend-artifacts:
    build:
      context: backend
      dockerfile: Dockerfile.prod.backend-artifacts
      args:
        - docker_host_ip