version: '3.8'

services:
  postgres:
    image: postgres:13.4-alpine3.14
    restart: always
    volumes:
      # Scripts only run it data directory is empty (from official docs)
      # - ./postgres/0.recreate.sql:/docker-entrypoint-initdb.d/0.recreate.sql
      - ./postgres/1.init.sql:/docker-entrypoint-initdb.d/1.init.sql
      # - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notepad
    command: ["postgres", "-c", "log_statement=all"]

  backend:
    # image: ...
    build:
      context: backend
      dockerfile: Dockerfile.prod
      args:
        - docker_host_ip
    environment:
      - TPG_DB=notepad
      - TPG_USER=admin
      - TPG_PASS=admin
      - TPG_HOST=db
      - TPG_PORT=5431
    ports:
      - '8000:8000'

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    environment:
      - BACKEND_URL=http://localhost:8000
    ports:
      - '8080:80'
