name:                haskell-spock
version:             0.1.0.0
github:              "githubuser/haskell-spock"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-spock#readme>

dependencies:
- base >= 4.7 && < 5
- Spock >= 0.14 # http server
- bytestring # for extracting postgres error messages
- containers # for Data.Map (for extracting postgres error messages)
- postgresql-typed # for compile-time typeckecking against real db
- network # for configuring db connection
- text # for efficient strings
- mtl # for monad transformers in general
- aeson # for JSON
- http-types # for specifying status codes for HTTP responses
- uuid # for UUIDs
- hvect # for specifying types for http request hooks
- fmt # for composing strings
- stm-chans # for stm-chans
- stm # for stm-chans

library:
  source-dirs: src

executables:
  haskell-spock-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-spock

tests:
  haskell-spock-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-spock
